### ISSUE TITLE
i cant open a world

### ISSUE THREAD

**Issue by Zado12** [ldtteam/Domum-Ornamentum#89] opened 2022-09-29 07:01 UTC
I have a problem with this mod, i cant open a world in my game and it seems that it is because of this mod

---- Minecraft Crash Report ----
// My bad.

Time: 2022-09-28 23:41:49
Description: Tesselating block model

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()'
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:204) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getBakedInnerModelFor(MateriallyTexturedBakedModel.java:198) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.getQuads(MateriallyTexturedBakedModel.java:90) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at net.minecraft.client.renderer.block.ModelBlockRenderer.renderModelFlat(ModelBlockRenderer.java:210) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:RebuildTaskMixin,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:RebuildTaskMixin,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()'
    at net.minecraftforge.client.model.IQuadTransformer.copy(IQuadTransformer.java:95) ~[forge-1.19.2-43.1.30-universal.jar%23181!/:?] {re:classloading}
    at net.minecraftforge.client.model.IQuadTransformer.process(IQuadTransformer.java:41) ~[forge-1.19.2-43.1.30-universal.jar%23181!/:?] {re:classloading}
    at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.lambda$retexture$3(RetexturedBakedModelBuilder.java:127) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
    at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.retexture(RetexturedBakedModelBuilder.java:125) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.lambda$build$0(RetexturedBakedModelBuilder.java:93) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
    at com.ldtteam.domumornamentum.client.model.baked.RetexturedBakedModelBuilder.build(RetexturedBakedModelBuilder.java:90) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at com.ldtteam.domumornamentum.client.model.baked.MateriallyTexturedBakedModel.lambda$getBakedInnerModelFor$4(MateriallyTexturedBakedModel.java:214) ~[domum_ornamentum-1.19-1.0.59-ALPHA-universal%20(1).jar%23156!/:1.19-1.0.59-ALPHA] {re:classloading}
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar%23115!/:?] {}
    ... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
    at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
-- Block model being tesselated --
Details:
    Block: Block{domum_ornamentum:shingle}[facing=north,half=bottom,shape=straight,waterlogged=false]
    Block location: World: (-592,80,612), Section: (at 0,0,4 in -37,5,38; chunk contains blocks -592,-64,608 to -577,319,623), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
    Using AO: false
Stacktrace:
    at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:RebuildTaskMixin,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:RebuildTaskMixin,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- Block being tesselated --
Details:
    Block: Block{domum_ornamentum:shingle}[facing=north,half=bottom,shape=straight,waterlogged=false]
    Block location: World: (-592,80,612), Section: (at 0,0,4 in -37,5,38; chunk contains blocks -592,-64,608 to -577,319,623), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
Stacktrace:
    at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:RebuildTaskMixin,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blue_skies.mixins.json:RebuildTaskMixin,pl:mixin:A}
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,xf:OptiFine:default}
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- Affected level --
Details:
    All players: 1 total; [LocalPlayer['G3isto'/71, l='ClientLevel', x=-580.92, y=73.00, z=610.34]]
    Chunk stats: 361, 201
    Level dimension: minecraft:overworld
    Level spawn location: World: (0,83,0), Section: (at 0,3,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
    Level time: 5354411 game time, 7237290 day time
    Server brand: forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:580) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:A}
    at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.m_231462_(Minecraft.java:800) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:690) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23176!/:?] {re:classloading,pl:runtimedistcleaner:A}
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
    at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.30.jar%2395!/:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
    at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
    Reload number: 1
    Reload reason: initial
    Finished: Yes
    Packs: Mod Resources, Default

-- System Details --
Details:
    Minecraft Version: 1.19.2
    Minecraft Version ID: 1.19.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 17.0.3, Microsoft
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
    Memory: 334989496 bytes (319 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
    CPUs: 4
    Processor Vendor: AuthenticAMD
    Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics    
    Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
    Microarchitecture: Zen / Zen+
    Frequency (GHz): 3.60
    Number of physical packages: 1
    Number of physical CPUs: 4
    Number of logical CPUs: 4
    Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
    Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
    Graphics card #0 VRAM (MB): 2048.00
    Graphics card #0 deviceId: 0x15d8
    Graphics card #0 versionInfo: DriverVersion=31.0.12019.9007
    Memory slot #0 capacity (MB): 8192.00
    Memory slot #0 clockSpeed (GHz): 2.40
    Memory slot #0 type: DDR4
    Virtual memory max (MB): 17842.76
    Virtual memory used (MB): 12807.41
    Swap memory total (MB): 11776.00
    Swap memory used (MB): 983.12
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    Launched Version: 1.19.2-forge-43.1.30
    Backend library: LWJGL version 3.3.1 build 7
    Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.0 Core Profile Context 22.8.2.220819, ATI Technologies Inc.
    Window size: 1366x768
    GL Caps: Using framebuffer using OpenGL 3.2
    GL debug messages: 
    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
    Type: Integrated Server (map_client.txt)
    Graphics mode: fancy
    Resource Packs: vanilla
    Current Language: Español (España)
    CPU: 4x AMD Ryzen 3 3200G with Radeon Vega Graphics 
    Server Running: true
    Player Count: 1 / 8; [ServerPlayer['G3isto'/71, l='ServerLevel[Mundo nuevo]', x=-580.92, y=73.00, z=610.34]]
    Data Packs: vanilla, mod:terrablender, mod:biomesoplenty, mod:jei (incompatible), mod:simplylight (incompatible), mod:domum_ornamentum, mod:sophisticatedcore (incompatible), mod:curios, mod:patchouli (incompatible), mod:xaerominimap, mod:waystones (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:gobber2, mod:magistuarmory, mod:sophisticatedbackpacks (incompatible), mod:balm (incompatible), mod:fallingtree, mod:forge, mod:geckolib3 (incompatible), mod:cataclysm (incompatible), mod:reap (incompatible), mod:croptopia (incompatible), mod:dungeoncrawl, mod:cfm (incompatible), mod:elevatorid (incompatible), mod:goblintraders (incompatible), mod:globalxp, mod:blue_skies, mod:torohealth, mod:guardvillagers (incompatible), mod:structure_gel
    World Generation: Stable
    OptiFine Version: OptiFine_1.19.2_HD_U_H9
    OptiFine Build: 20220820-230904
    Render Distance Chunks: 6
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: ComplementaryShaders_v4.5 (1).zip
    OpenGlVersion: 3.2.0 Core Profile Context 22.8.2.220819
    OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
    OpenGlVendor: ATI Technologies Inc.
    CpuCount: 4
    ModLauncher: 10.0.8+10.0.8+main.0ef7e830
    ModLauncher launch target: forgeclient
    ModLauncher naming: srg
    ModLauncher services: 
        mixin-0.8.5.jar mixin PLUGINSERVICE 
        eventbus-6.0.3.jar eventbus PLUGINSERVICE 
        fmlloader-1.19.2-43.1.30.jar slf4jfixer PLUGINSERVICE 
        fmlloader-1.19.2-43.1.30.jar object_holder_definalize PLUGINSERVICE 
        fmlloader-1.19.2-43.1.30.jar runtime_enum_extender PLUGINSERVICE 
        fmlloader-1.19.2-43.1.30.jar capability_token_subclass PLUGINSERVICE 
        accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
        fmlloader-1.19.2-43.1.30.jar runtimedistcleaner PLUGINSERVICE 
        modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
        modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
        modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
    FML Language Providers: 
        minecraft@1.0
        lowcodefml@null
        javafml@null
    Mod List: 
        client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
        TerraBlender-forge-1.19.2-2.0.1.125.jar           |TerraBlender                  |terrablender                  |2.0.1.125           |DONE      |Manifest: NOSIGNATURE
        blue_skies-1.19.2-1.3.20.jar                      |Blue Skies                    |blue_skies                    |1.3.20              |DONE      |Manifest: NOSIGNATURE
        BiomesOPlenty-1.19.2-17.1.1.150.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.150          |DONE      |Manifest: NOSIGNATURE
        jei-1.19.2-forge-11.2.0.256.jar                   |Just Enough Items             |jei                           |11.2.0.256          |DONE      |Manifest: NOSIGNATURE
        simplylight-1.19-1.4.4-build.39 (1).jar           |Simply Light                  |simplylight                   |1.19-1.4.4-build.39 |DONE      |Manifest: NOSIGNATURE
        domum_ornamentum-1.19-1.0.59-ALPHA-universal (1).j|Domum Ornamentum              |domum_ornamentum              |1.19-1.0.59-ALPHA   |DONE      |Manifest: NOSIGNATURE
        goblintraders-1.7.3-1.19.jar                      |Goblin Traders                |goblintraders                 |1.7.3               |DONE      |Manifest: NOSIGNATURE
        torohealth-1.19-forge-2 (1).jar                   |ToroHealth                    |torohealth                    |1.19-forge-2        |DONE      |Manifest: NOSIGNATURE
        sophisticatedcore-1.19.2-0.5.1.97.jar             |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.1.97     |DONE      |Manifest: NOSIGNATURE
        reap-1.19.2-1.0.0.jar                             |Reap Mod                      |reap                          |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
        curios-forge-1.19.2-5.1.1.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.1.0      |DONE      |Manifest: NOSIGNATURE
        Patchouli-1.19.2-76.jar                           |Patchouli                     |patchouli                     |1.19.2-76           |DONE      |Manifest: NOSIGNATURE
        Xaeros_Minimap_22.13.2_Forge_1.19.1.jar           |Xaero's Minimap               |xaerominimap                  |22.13.2             |DONE      |Manifest: NOSIGNATURE
        waystones-forge-1.19-11.1.0 (1).jar               |Waystones                     |waystones                     |11.1.0              |DONE      |Manifest: NOSIGNATURE
        Croptopia-1.19.2-FORGE-2.1.0.jar                  |Croptopia                     |croptopia                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
        citadel-1.12.7-1.19 (1).jar                       |Citadel                       |citadel                       |1.12.7              |DONE      |Manifest: NOSIGNATURE
        alexsmobs-1.19.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.19.5              |DONE      |Manifest: NOSIGNATURE
        Cataclysm-0.20-1.19.2-hotfix.jar                  |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
        elevatorid-1.19-1.8.7.jar                         |Elevator Mod                  |elevatorid                    |1.19-1.8.7          |DONE      |Manifest: NOSIGNATURE
        Gobber2-Forge-1.19.2-2.7.10.jar                   |Gobber 2                      |gobber2                       |2.7.10              |DONE      |Manifest: NOSIGNATURE
        [1.19.x]-Epic-Knights-Armor-and-Weapons-6.6v.jar  |Epic Knights: Armor and Weapon|magistuarmory                 |1.0                 |DONE      |Manifest: NOSIGNATURE
        DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |DONE      |Manifest: NOSIGNATURE
        sophisticatedbackpacks-1.19.2-3.18.17.679.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.17.679  |DONE      |Manifest: NOSIGNATURE
        guardvillagers-1.19.2-1.5.2.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.2        |DONE      |Manifest: NOSIGNATURE
        cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |DONE      |Manifest: NOSIGNATURE
        globalxp-1.19-1.10.2.jar                          |Global XP                     |globalxp                      |1.10.2              |DONE      |Manifest: NOSIGNATURE
        balm-4.5.3 (1).jar                                |Balm                          |balm                          |4.5.3               |DONE      |Manifest: NOSIGNATURE
        FallingTree-1.19.2-3.9.2.jar                      |FallingTree                   |fallingtree                   |3.9.2               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
        forge-1.19.2-43.1.30-universal.jar                |Forge                         |forge                         |43.1.30             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
        geckolib-forge-1.19-3.1.19.jar                    |GeckoLib                      |geckolib3                     |3.1.19              |DONE      |Manifest: NOSIGNATURE
        structure_gel-1.19.2-2.6.2.jar                    |Structure Gel API             |structure_gel                 |2.6.2               |DONE      |Manifest: NOSIGNATURE
    Crash Report UUID: a6d4072a-2b76-44b0-a50c-b48427eeca5f
    FML: 43.1
    Forge: net.minecraftforge:43.1.30

**Comment by MotionlessTrain** [comment] 2022-09-29 07:07
Duplicate of #84 

Domum Ornamentum is not yet compatible with optifine in 1.19

**Comment by Zado12** [comment] 2022-09-29 07:18
> Duplicado de #84
> 
> Domum Ornamentum aún no es compatible con optifine en 1.19

thanks

**Closed as completed** 2022-09-29 07:54 UTC
