### ISSUE TITLE
Materials dont have a "right" tool to harvest it in short time

### ISSUE THREAD

**Issue by f0kx** [ldtteam/Domum-Ornamentum#104] opened 2022-11-09 15:19 UTC
When i want to break the Blocks of Demum Ornamentum it needs very long to break it.
I have JADE Mod installed and there is no tool i can use for breaking it faster.

**Comment by MotionlessTrain** [comment] 2022-11-09 16:17
Duplicate of #76 and #60

**Comment by MotionlessTrain** [comment] 2022-11-09 16:19
The issue is that they are exactly the same block, independent of the materials used to make it. Using a pickaxe is strange for wooden framed blocks, and an axe is strange for stone framed blocks

**Comment by f0kx** [comment] 2022-11-09 16:31
so breaking a block taking 10 seconds each is solution?

**Comment by MotionlessTrain** [comment] 2022-11-09 20:09
No, both of the linked issues provide a solution. I just explained the reason of the issue

**Comment by Veranidae** [comment] 2022-12-08 02:41
it seems the axe is the right tool, at least for the panels. i'm using the one probe and although it _says_ there's no designated tool, when i hold the axe it changes to a check mark and the block seems to break faster

**Closed as completed** 2024-07-14 08:47 UTC
