### ISSUE TITLE
[1.20.1] Client Crash when placing a Fancy Door from Domum Ornamentum

### ISSUE THREAD

**Issue by jamieb999** [ldtteam/Domum-Ornamentum#218] opened 2024-01-28 02:47 UTC
Please read the ticket all the way though updated to 
domum_ornamentum-1.20-1.0.154-BETA-universal
and it is still crashing.

Server is Neoforged 1.20.1  (forge-1.20.1-47.1.91)

Any time you try and place the Fancy White Door 
at  a Minecolonies structure the client crashes. 

Version: domum_ornamentum-1.20-1.0.151-BETA-universal

I am in creative mode as well while this is crashing. 

The exact error message is 

"The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: No enum constant com.ldtteam.domumornamentum.block.types.FancyDoorType."

And from part of the cash log 

"java.lang.IllegalArgumentException: No enum constant com.ldtteam.domumornamentum.block.types.FancyDoorType.
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {re:mixin}
	at com.ldtteam.domumornamentum.block.types.FancyDoorType.valueOf(FancyDoorType.java:9) ~[domum_ornamentum-1.20-1.0.151-BETA-universal.jar%23350!/:1.20-1.0.151-BETA] {re:classloading}
	at com.ldtteam.domumornamentum.block.decorative.FancyDoorBlock.m_6402_(FancyDoorBlock.java:145) "

A screenshot of the crashed minecraft client can be seen at 
https://ibb.co/VMz0n2d

I am using the stock minecraft client v2.16.12.-1.7.2

![Minecraft Java Edition Domum Ornamentum Fancy Door January 27 2024](https://github.com/ldtteam/Domum-Ornamentum/assets/115375746/90e3ce94-d483-4368-9927-361dc37f128a)

It clearly makes mention that it is your Fancy Door that caused the crash. 

Windows 10 Pro for the PC running Minecraft Java.  16 GB of RAM. 

Java 17 

java --version
java 17.0.10 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)

It is consitently crashing too.  It crashed one before when I tried to place this same door
and it just did it again and has done it at least 3 times now every time  I try and place a 
the door at the doorway it crashes.

/give @p domum_ornamentum:fancy_door 1

Try and place the door from the outside and it crashes. 

The structure is the house from Minecolonies the Villa.  I am trying to
place the door from the outside. 

Fundementals > Residents > Villa from the  Buildtool for Minecolonies. 

The structurue I am placing it at is from MineColonies the door acidently got removed
and then I am trying to replace it and it crashes when I stand outside of the building and
try and place the door. 

So you can see the structure from MineColonies that I am trying to replace
the door at I have uploaded a couple of pictures of the villa I am trying to replace
the door on.  This door matchs the other doors on the Villa when you mouse over other 
doors on the structure it is the same door. 

https://ibb.co/74vQt4q
https://ibb.co/R4kzQ2Y

![2024-01-27_20 08 50](https://github.com/ldtteam/Domum-Ornamentum/assets/115375746/dbd83c03-da84-4036-8b69-70249f48b49c)

I am standing from the outside of the structure and trying to place the
door when I try and place the door the minecraft java stock
client crashes. 

![2024-01-27_20 09 04](https://github.com/ldtteam/Domum-Ornamentum/assets/115375746/2ffb4a4d-1048-408f-90ff-4bbe95d39bf6)

The crash report can be seen at the link bellow. 
https://pastebin.com/pP53u13k

[crash-2024-01-27_19.15.49-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/14074684/crash-2024-01-27_19.15.49-client.txt)

I did look at the open tickets and never saw one directly related to the same Fancy Door that
I am reporting so I am opening this new ticket. Can you please look at fixing this 
issue please.  It only seems to crash the client side not the server which is strange. 

More information about the PC running the Minecraft Java client  incase 
you need it. 

[DxDiag.txt](https://github.com/ldtteam/Domum-Ornamentum/files/14074730/DxDiag.txt)

UPDATE: 

And I wemt to  domum_ornamentum-1.20-1.0.154-BETA-universal.jar
And same issue! 

https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files/5059422
Same error code with 1.20-1.0.154-BETA-universal same crash with the fancy door.

Time: 2024-01-27 20:48:37
Description: Unexpected error

java.lang.IllegalArgumentException: No enum constant com.ldtteam.domumornamentum.block.types.FancyDoorType.
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {re:mixin}
	at com.ldtteam.domumornamentum.block.types.FancyDoorType.valueOf(FancyDoorType.java:9) ~[domum_ornamentum-1.20-1.0.154-BETA-universal.jar%23350!/:1.20-1.0.154-BETA] {re:classloading}
	at com.ldtteam.domumornamentum.block.decorative.FancyDoorBlock.m_6402_(FancyDoorBlock.java:145) ~[domum_ornamentum-1.20-1.0.154-BETA-universal.jar%23350!/:1.20-1.0.154-BETA] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:BlockItemMixin,pl:mixin:APP:puzzleslib.common.mixins.json:accessor.BlockItemAccessor,pl:mixin:APP:ad_astra-common.mixins.json:oxygen.BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:BlockItemMixin,pl:mixin:APP:puzzleslib.common.mixins.json:accessor.BlockItemAccessor,pl:mixin:APP:ad_astra-common.mixins.json:oxygen.BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.lambda$useOn$3(ItemStack.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:redirector.mixins.json:net.minecraft.world.item.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:redirector.mixins.json:net.minecraft.world.item.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:redirector.mixins.json:net.minecraft.world.item.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:canary.mixins.json:util.item_stack_tracking.ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:336) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:redirector.mixins.json:net.minecraft.client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:fastload.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:redirector.mixins.json:net.minecraft.client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:fastload.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:redirector.mixins.json:net.minecraft.client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:fastload.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:redirector.mixins.json:net.minecraft.client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:fastload.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:redirector.mixins.json:net.minecraft.client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:botania_xplat.mixins.json:client.MinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:fastload.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.91.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

The full logs for  domum_ornamentum-1.20-1.0.154-BETA-universal is at 

https://pastebin.com/EjtjQBWs

New logs for domum_ornamentum-1.20-1.0.154-BETA-universal 
are also bellow.

[crash-2024-01-27_20.48.36-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/14074841/crash-2024-01-27_20.48.36-client.txt)

**Comment by Talyda** [comment] 2024-01-28 02:59
Try updating DO and see if that fixes it. Can't remember what, but something was fixed in the past couple versions for a crash

**Comment by jamieb999** [comment] 2024-01-28 03:03
I am updated and it is not fixed.  You don't even know what was fixed

You said in your post 

"Can't remember what, but something was fixed in the past couple versions for a crash"

So if you don't know if this is even the same bug with the same item then
why did you comment? 

You don't even know if what was fixed is even related to this bug or not by 
your own comment. 

I can tell you that I went to 
domum_ornamentum-1.20-1.0.154-BETA-universal
https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files/5059422

And it is not fixed.  It crashed again.  This is a NEW bug that is not fixed

**Comment by Raycoms** [comment] 2024-01-28 07:32
{re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:BlockItemMixin,pl:mixin:APP:puzzleslib.common.mixins.json:accessor.BlockItemAccessor,pl:mixin:APP:ad_astra-common.mixins.json:oxygen.BlockItemMixin,pl:mixin:A}


One of these. moonlight common or ad astra or so I would guess as culprits.

**Comment by jamieb999** [comment] 2024-01-29 07:33
Look this mod should play nice with other mods I was on the discord channel and met a very hostile individual I guess who is the developer and I don't think I'm going to get much help with this problem so I will probably end up removing both mine colonies and DO.

I still stand by that this is a problem with DO
and hopefully this get fixed.

I mean the mods should play nice with other mods or add a feature to blacklist mods that won't play nice with DO. But mine colonies and DO should play nice together but they are not.

When I was on the discord channel for this group I felt like I was in highschool in the principles office getting reamed out.

I know other mods have the ability to blacklist mods that don't interact well with their mods I have mods like that already. There must be a way to fix this.

I felt more like I was being interrogated and as I told the dev there I am a trained person in the IT field myself I am not ur typical end user here.
 Moonlight is a library API that my other mods need I can't remove that or it will end up breaking other mods.

**Comment by Thodor12** [comment] 2024-01-29 07:40
> /give @p domum_ornamentum:fancy_door 1

You cannot spawn Domum blocks in creative, they must be made using an architects cutter, otherwise they are missing material data, which will cause that crash.

**Comment by jamieb999** [comment] 2024-01-29 07:46
Wow I mean this mod that messed up that u can't spawn the blocks without it crashing that alone shows the mod needs to be fixed that's horrible. 

That needs to be fixed u should be able to use the commands to give yourself the block if u can't that is a huge flaw in the mod and it needs to be fixed. 

I play in creative mode period the mod should be able to handle people giving themselves a block.

That definitely needs to be fixed

**Comment by Thodor12** [comment] 2024-01-29 07:49
It's technically possible if you provide NBT data in the command. But Domum blocks exist out of random materials, you can't just spawn it without giving any kind of extra information.

**Comment by Thodor12** [comment] 2024-01-29 07:50
That's the whole reason those blocks show up with constant changing materials in creative tabs/JEI

**Comment by marchermans** [comment] 2024-01-29 08:04
## Closing this ticket for ldtteam community guideline violations

After the poster verbally abused support personal, violated our license, and reacted aggresive to our community members, when told that we needed to perform more tests, because we could not reproduce her issue: This ticket has been closed.

If you have this issue as well. Please open a new ticket.

**Closed as not planned by marchermans** 2024-01-29 08:04 UTC
