### ISSUE TITLE
Crashed when I opened my inventory with JEI installed

### ISSUE THREAD

**Issue by robbenrose** [ldtteam/Domum-Ornamentum#88] opened 2022-09-27 15:22 UTC
[crash-2022-09-27_10.19.06-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9657426/crash-2022-09-27_10.19.06-client.txt)

**Comment by Talyda** [comment] 2022-09-28 02:28
You're using optifine. Try without. It's not supported in 1.19 yet

**Comment by MotionlessTrain** [comment] 2022-09-28 05:25
Duplicate of #84

**Closed as completed** 2022-09-29 07:54 UTC
