### ISSUE TITLE
Missing block translations

### ISSUE THREAD

**Issue by uecasm** [ldtteam/Domum-Ornamentum#116] opened 2022-12-27 04:19 UTC
Many DO blocks (as blocks, not items) seem to lack translation entries.

See the "Block Tags" tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1DaGFlFcnce4bHXHylzztr5_Rwnm3P42c6o_xXqgyyr8/edit?usp=sharing) for the full list; this was generated with DO 1.19-1.0.76-ALPHA.

(This also shows that several blocks lack a preferred tool via `mineable` tags...)

**Comment by marchermans** [comment] 2022-12-27 11:26
Yes this is known and not a problem.
The block translations are not user facing and for many do blocks we could not find a good compromise tool, but since it heavily depends on the materials used.

Closing as working as intended

**Comment by uecasm** [comment] 2022-12-27 11:49
If the user is using a tool like Hwyla or Jade then the names are user facing.  They also appear in the F3 menu, and they can also appear in the Structurize entity list menu when the blocks are item entities on the ground.

Also almost all of the cited blocks that have problems are the static "extra" blocks, that absolutely can have a proper name.  Not the materially textured blocks.  So this is unquestionably a bug.

**Closed as completed** 2024-07-14 08:45 UTC
