### ISSUE TITLE
1.19.2 Forge 43.2.0 Issues with ''Reforgium/Connectedness''

### ISSUE THREAD

**Issue by Totomio** [ldtteam/Domum-Ornamentum#150] opened 2023-06-16 14:33 UTC
I encountered missing tiles with Domum-Ornamentum installed alongside Reorgium/Connectedness.
Here are 2 screenshots, the first with Reorgium/connectedness installed, the second without.
The issue occurs on doors crafted with at least 2 different materials (it doesn't matter which ones) placed in the 3 Architects cutter slots. Using 2 slots does not trigger the issue.

With Reforgium/connectedness :
![Domum ornamentum - Reforgium-Connectedness 1](https://github.com/ldtteam/Domum-Ornamentum/assets/71310604/5ee159ef-bed2-4831-ba00-360334fc67bc)

Without Reforgium/connectedness :
![Domum ornamentum -Without Reforgium-Connectedness 1](https://github.com/ldtteam/Domum-Ornamentum/assets/71310604/33d89951-8955-4c34-b217-923debc03883)

Reforgium/connectedness provide connected texture feature from optifine without optifine
Note : I reported the problem in the connectedness tracked issues section also
-> https://github.com/Asek3/Connectedness/issues/14

**Comment by marchermans** [comment] 2023-06-16 16:36
This i caused by the rendering mod.
We use forges rendering engine components to support the material information choice.

As such we consider this a third-party issue and will close this ticket.

**Closed as not planned by marchermans** 2023-06-16 16:36 UTC
