### ISSUE TITLE
Inventory tab

### ISSUE THREAD

**Issue by dggzvtii** [ldtteam/Domum-Ornamentum#93] opened 2022-10-05 14:37 UTC
If you Click to the "Domum Ornamentum (DO)" Creative inventory tab,
the game crasches

**Comment by MotionlessTrain** [comment] 2022-10-05 15:01
Are you using optifine in 1.19? If so, this is a duplicate of #84 
If not, could you please provide version info and logs?

**Comment by dggzvtii** [comment] 2022-10-05 15:06
Yes, I was Using Optifine.
Thank you.

**Closed as not planned** 2022-10-05 15:18 UTC
