### ISSUE TITLE
Crashing game on 1.19.2

### ISSUE THREAD

**Issue by Frizsky** [ldtteam/Domum-Ornamentum#122] opened 2023-01-16 17:44 UTC
On game version 1.19.2.  Have only domum ornamentum-
1.19-1.0.76-ALPHA…. Or below and whit 1.19.2 it don’t run together , game crashing

**Comment by MotionlessTrain** [comment] 2023-01-16 19:57
Could you provide your crash log please?

**Comment by Frizsky** [comment] 2023-01-17 12:04
I take off the mod , as it didt run together whit minecolonies and other what are mention , checking crash  log was  (incompatible) . Downloaded 2 times , but all time when on creative open whit structurazer game crash or in surv.   Or , this problem is not about domum ornamentum or other what don’t let open .

**Comment by MotionlessTrain** [comment] 2023-01-17 12:13
If you would provide the crash log, we can see what the issue is

**Comment by MachoMan1997** [comment] 2023-01-18 00:29
I have the same issue, while loading 20+ mods and also while loading only MineColonies and Domum Ornamentum. The crash seens to happen whenever I search for D.O. items in Creative inventory or JEI. I`ll drop the crash log part that I think might help figure it out:

[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in domum_ornamentum:block/doors/door_waffle_top_right_open_spec
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in domum_ornamentum:block/trapdoors/trapdoor_waffle_spec
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in domum_ornamentum:block/doors/door_waffle_top_left_spec
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in domum_ornamentum:block/doors/door_waffle_top_left_open_spec
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in domum_ornamentum:block/doors/door_waffle_top_right_spec
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in multipiston:block/multipistonblock
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in multipiston:item/multipistonblock
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in waterstrainer:item/worm_bin
[21:20:41] [Worker-Main-1/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missing in waterstrainer:block/worm_bin


Complete log is attached.


[tl-logger6101338362879314534.txt](https://github.com/ldtteam/Domum-Ornamentum/files/10440684/tl-logger6101338362879314534.txt)

**Comment by Talyda** [comment] 2023-01-18 00:32
> Complete log is attached.
> 
> [tl-logger6101338362879314534.txt](https://github.com/ldtteam/Domum-Ornamentum/files/10440684/tl-logger6101338362879314534.txt)

Oh, I didn't notice the cracked launcher. Removing my comment now =P

**Comment by MotionlessTrain** [comment] 2023-01-18 00:35
> Complete log is attached.
> 
> [tl-logger6101338362879314534.txt](https://github.com/ldtteam/Domum-Ornamentum/files/10440684/tl-logger6101338362879314534.txt)

We don't support or tolerate cracked launchers

**Comment by Frizsky** [comment] 2023-01-18 00:46
Thank you for the message back to get clear whit my  crash report .

I had the same problem whit mods on or off , it had same problem . Opening
inventory game throw me out .

Yes , I do play whit optif.  If that’s the problem I will take it off and
try to put it again whit other ones what “minecolonies “ requires.

**Comment by marchermans** [comment] 2023-01-18 05:29
Given that the user uses a cracked launcher with changes that are impossible for us to verify: I am closing this issue.

**Closed as not planned by marchermans** 2023-01-18 05:29 UTC
